name: Addon
authors: [kezukdev, Greentor]
version: 1.0
description: Practice api maded by Akyto developers teams.
main: akyto.practice.Practice
depend:
  - Universal
commands:
  duel:
    aliases: [d, duels]
  settings:
    aliases: [parameters, parameter, setting]
  locations:
    aliases: [loc]
  arena:
    aliases: [map, battlearena, arenas]
  stats:
    aliases: [profile, statistics, elo]
  spectate:
    aliases: [spec, view]
  inventory:
    aliases: [inv, inventories]
  leaderboard:
    aliases: [lb, leaderb, top, leadertop]
  party:
    aliases: [p, group, parties]
  reset:
    aliases: [statsreset, tweak]
    description: 'Reset global data of targeted player!'
  showcase:
    aliases: [pack, resourcepack]
    description: "Send the player to the resource pack showcase room."
  