name: Practice
author: [kezukdev]
version: 1.0
description: Akyto practice developed by Kezuk
main: kezukdev.akyto.Practice
commands:
  duel:
    aliases: [d, duels]
  settings:
    aliases: [parameters, parameter, setting]
  locations:
    aliases: [loc]
  arena:
    aliases: [map, battlearena, arenas]
  stats:
    aliases: [profile, statistics, elo]
  spectate:
    aliases: [spec, view]
  inventory:
    aliases: [inv, inventories]
  leaderboard:
    aliases: [lb, leaderb, top, leadertop]
  party:
    aliases: [p, group, parties]
  